name: build-push

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: "5.6.2-jammy: Build and push"
        uses: docker/build-push-action@v3
        with:
          context: .
          file: 5.6/ubuntu/22.04/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: gohanlon/swift:5.6.2-jammy
      -
        name: "5.6.2-jammy-slim: Build and push"
        uses: docker/build-push-action@v3
        with:
          context: .
          file: 5.6/ubuntu/22.04/slim/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: gohanlon/swift:5.6.2-jammy-slim
